[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mplchart"
version = "0.0.11"
requires-python = ">=3.9"
readme = "output/README.md"
license = { text = "MIT License" }
description = "Classic Stock Charts in Python"
urls = { homepage = "https://github.com/furechan/mplchart" }
authors = [{ name = "Furechan", email = "furechan@xsmail.com" },
            { name = "syntaxsdev", email = "sidsyntaxs@gmail.com"}]
keywords = ["finance", "charting", "matplotlib", "candlesticks"]
dependencies = ["matplotlib", "yfinance", "numpy", "pandas"]
optional-dependencies.dev = ["pytest", "pytest-sugar", "ipykernel"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.build]
targets.wheel.sources = ["src"]
dev-mode-dirs = ["src"]
only-include = ["src"]
exclude = [".*"]

[tool.pydev]
allow-publish = true

[tool.pytest.ini_options]
addopts = ["-p no:cacheprovider"]
testpaths = ["tests"]
